export const projects = [
    {
        name: 'Bula - live ecommerce store',
        date:'June 19, 2022',
        about: 'A live ecommerce website using Shopify.',
        tools:["Next", "Tailwind", "Storefront API", "Vercel"],
        resposLink: "https://github.com/eds2002/devecom",
        webLink:'https://www.bulamics.com',
        featured:true,
        type:'crud',
    },
    {
        name: "CRUD Blog App",
        date: 'May 26, 2022',
        about: "A fully functional Blog app. Read more on the blog site!",
        tools: ["Next", "Node", "Express", "Styled Components", "Tailwind", "Mysql", "Heroku", "Netlify"],
        resposLink: 'https://github.com/eds2002/Blog-Crud-Fullstack-app',
        webLink: 'https://blogappfrontend.vercel.app/',
        featured:true,
        type: 'crud'
    },
    {
        name: "Thousand Prompts",
        date: 'February 2, 2022',
        about: "A Journal Pwa, Thousand Prompts combines C.B.T therapy and journaling.",
        tools: ["HTML", "Css", "Scss", "Javscript", "Firebase", "Firebase Hosting", "PWA"],
        resposLink: "https://github.com/eds2002/thousand-prompts",
        webLink: "https://www.thousandprompts.com",
        featured:true,
        type:'api',
    },
    {
        name: "Ticket Sensei",
        date: 'April 24, 2022',
        about: "Uses the Ticket Master API to locate popular attractions.",
        tools: ["Next","Ticket Master Api", "Styled Components"],
        resposLink: "https://github.com/eds2002/ticketsensei",
        webLink: "https://ticketsense.vercel.app/",
        featured:false,
    },
    {
        name: "Fake Ecom",
        about: "A fake ecom headphone store.",
        tools: ["Next", "Sanity IO", "Stripe", "Vercel"],
        resposLink: "https://github.com/eds2002/fake_ecom",
        webLink: "https://fake-ecom.vercel.app/",
        featured:false,
    },
    {
        name: "Yoga Website",
        about: "A website designed for my local yoga place.",
        tools: ["Next", "Tailwind", "Netlify","Git"],
        resposLink: "https://github.com/eds2002/yoga-landing-page",
        webLink: "https://radiant-kulfi-361fc2.netlify.app/",
        featured:false,
    },
    {
        name: "User Management System",
        date: 'May 19, 2022',
        about:"A user management CRUD application.",
        tools: ["React", "Tailwind", "MySQL", "Node", "Express", "Redux"],
        resposLink : "https://github.com/eds2002/usermanagement",
        webLink : "https://aquamarine-dragon-f2a57c.netlify.app/",
        featured:false,
        type:'crud',
    },
    {
        name:'My First Webstite',
        date:'October, 22, 2021',
        about:"Take a look at my first website and see how far I came!",
        tools: ['HTML', 'CSS'],
        resposLink: 'https://github.com/eds2002/my-first-website',
        webLink:'https://willowy-pegasus-69f070.netlify.app/',
        featured:false,
        type:'none'
    }
]